### ISSUE TITLE
user subdir in VO dir should not have 700 perm, but 750 (or maybe 770)

### ISSUE THREAD

**Issue by stdweird** [hpcugent/vsc-administration#13]

**Comment by itkovian** [comment]
I would argue that these need to be 0700 upon creation of the dir, but should never be altered back to the default, so users can change them. The reason is that somebody might belong to a VO (to obtain extra storage space), but the work might be confidential and should thus not be accessible to the group. Hence, an initial 0700 setting is safer and meets the above.
